// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTable.Data;

#nullable disable

namespace TimeTable.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241205174429_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TimeTable.Core.Entity.AvailabilityEntity", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"), 1L, 1);

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWholeDayOff")
                        .HasColumnType("bit");

                    b.Property<int?>("TeacherEntityTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Unavailablehours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isMust")
                        .HasColumnType("bit");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("TeacherEntityTeacherId");

                    b.ToTable("_Availabilities");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.ClassEntity", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"), 1L, 1);

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalWeekHours")
                        .HasColumnType("int");

                    b.HasKey("ClassId");

                    b.ToTable("_Classes");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.ClassSubjectEntity", b =>
                {
                    b.Property<int>("ClassSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassSubjectId"), 1L, 1);

                    b.Property<int?>("ClassEntityClassId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("HoursPersWeek")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ClassSubjectId");

                    b.HasIndex("ClassEntityClassId");

                    b.ToTable("ClassSubjectEntity");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.SubjectEntity", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"), 1L, 1);

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("_Subjects");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.TeacherClassSubjectEntity", b =>
                {
                    b.Property<int>("TeacherClassSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherClassSubjectId"), 1L, 1);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherEntityTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("TeacherClassSubjectId");

                    b.HasIndex("TeacherEntityTeacherId");

                    b.ToTable("TeacherClassSubjectEntity");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.TeacherEntity", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalWeeklyHours")
                        .HasColumnType("int");

                    b.HasKey("TeacherId");

                    b.ToTable("_Teachers");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.AvailabilityEntity", b =>
                {
                    b.HasOne("TimeTable.Core.Entity.TeacherEntity", null)
                        .WithMany("Availabilities")
                        .HasForeignKey("TeacherEntityTeacherId");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.ClassSubjectEntity", b =>
                {
                    b.HasOne("TimeTable.Core.Entity.ClassEntity", null)
                        .WithMany("Subjects")
                        .HasForeignKey("ClassEntityClassId");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.TeacherClassSubjectEntity", b =>
                {
                    b.HasOne("TimeTable.Core.Entity.TeacherEntity", null)
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherEntityTeacherId");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.ClassEntity", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("TimeTable.Core.Entity.TeacherEntity", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
